### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by wernight**
Make entry point phantomjs so commands can be simplified to:

$ docker run --rm cmfatih/phantomjs --webdriver=8910

### CODE REVIEW

**Comment by cmfatih** [comment]
I'm gonna merge the changes. Thanks for the PR...

**Comment by devsli** [comment]
Something gone wrong and my CasperJS is broken now:
```bash
$ docker run cmfatih/phantomjs /usr/bin/phantomjs -v
phantomjs> $

$ docker run cmfatih/phantomjs /usr/bin/casperjs --version
phantomjs> $

$ docker run --rm cmfatih/phantomjs --entrypoint="/bin/sh"
phantomjs> $ # Huh?!
```

I'll create issue a bit later.

**Comment by s17t** [comment]
+1, it's broken.

**Comment by wernight** [comment]
It's a breaking change but it's not broken.

Correct commands would be:
````
$ docker run --rm cmfatih/phantomjs -v
$ docker run --rm cmfatih/phantomjs --version
$ docker run --rm --entrypoint="/bin/sh" cmfatih/phantomjs
# 
````

Normally you don't need bash hence the entrypoint change.

**Pull request merged**
